# Site settings
title: Prims Studio
description:
url:

# Page default settings
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            locale: zh
            portal:
                top: off
                top-margin-class: "txt-white bg-transparent"
                top-content-class: "txt-white bg-black header-emphasis"
                top-image-fullsize: true
                bottom: off
                bottom-content-class: "txt-white bg-grey header-emphasis"
                bottom-image-fullsize: true

# Jekyll settings
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Gem settings
gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE"]
