# Site settings
title: Prims Studio
description:
url: http://www.prims-studio.de
locales: ["de", "en", "zh"]
default_locale: de

# Settings
sass:
  style: compressed
permalink: /:categories/:title/
future: true
exclude: ["README.md"]

# Plugins
plugins:
  - jekyll-sitemap
