# Site settings
title: Prims Studio
description:
url: http://www.prims-studio.de
locales: ["en", "zh"]
default_locale: en

# Page default settings
defaults:
    -   scope:
            path: ""
        values:
            portal:
                top: off
                top_margin_class: "txt-white bg-transparent"
                top_content_class: "txt-white bg-black header-emphasis"
                top_image_fullsize: true
                bottom: off
                bottom_content_class: "txt-white bg-grey header-emphasis"
                bottom_image_fullsize: true
            locale: en
            locale_menu: on

# Jekyll settings
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Gem settings
gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE"]
