# Site settings
title: Prims Studio
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:

# Page default settings
defaults:
    -
        scope:
            path: ""
        values:
            portal:
                top: off
                top-margin-class: "txt-white bg-transparent"
                top-content-class: "txt-white bg-black header-emphasis"
                top-image-fullsize: true
                bottom: off
                bottom-content-class: "txt-white bg-grey header-emphasis"
                bottom-image-fullsize: true
    -
        scope:
            path: ""
            type: "posts"
        values:
            portal:
                top-image-fullsize: false
                bottom-image-fullsize: false
            post-content-class: "txt-black bg-white header-emphasis"
    -
        scope:
            path: ""
            type: "drafts"
        values:
            portal:
                top-image-fullsize: false
                bottom-image-fullsize: false
            post-content-class: "txt-black bg-white header-emphasis"

# Jekyll settings
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Gem settings
gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE"]
