# Site settings
title: Prims Studio
description:
url:
default_locale: zh

# Page default settings
defaults:
    -   scope:
            path: ""
        values:
            locale: zh
            portal:
                top: off
                top_margin_class: "txt-white bg-transparent"
                top_content_class: "txt-white bg-black header-emphasis"
                top_image_fullsize: true
                bottom: off
                bottom_content_class: "txt-white bg-grey header-emphasis"
                bottom_image_fullsize: true

    -   scope:
            path: ""
            type: "posts"
        values:
            portal:
                top_image_fullsize: false
                bottom_image_fullsize: false
            post_content_class: "txt-black bg-white header-emphasis"

    -   scope:
            path: ""
            type: "drafts"
        values:
            portal:
                top_image_fullsize: false
                bottom_image_fullsize: false
            post_content_class: "txt-black bg-white header-emphasis"

# Jekyll settings
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Gem settings
gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE"]
