# Site configuration
title: Prims Studio
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Gem configuration
gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE"]
